// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NissensVerksted.Data;

#nullable disable

namespace NissensVerksted.Migrations
{
    [DbContext(typeof(VerkstedDbContext))]
    partial class VerkstedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NissensVerksted.Models.Alv", b =>
                {
                    b.Property<int>("AlvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avdeling")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Erfaring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Spesialitet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AlvId");

                    b.HasIndex("Spesialitet");

                    b.ToTable("Alver");

                    b.HasData(
                        new
                        {
                            AlvId = 1,
                            Avdeling = "Produksjon",
                            ErAktiv = true,
                            Erfaring = 150,
                            Navn = "Bjørnis Hammerhand",
                            Spesialitet = "Tresnikring"
                        },
                        new
                        {
                            AlvId = 2,
                            Avdeling = "Teknologi",
                            ErAktiv = true,
                            Erfaring = 75,
                            Navn = "Elina Elektronikk",
                            Spesialitet = "Elektronikk"
                        },
                        new
                        {
                            AlvId = 3,
                            Avdeling = "Design",
                            ErAktiv = true,
                            Erfaring = 200,
                            Navn = "Turid Tøysterk",
                            Spesialitet = "Tekstiler"
                        });
                });

            modelBuilder.Entity("NissensVerksted.Models.Barn", b =>
                {
                    b.Property<int>("BarnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Alder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NiceScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ØnskelisteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BarnId");

                    b.HasIndex("NiceScore");

                    b.HasIndex("ØnskelisteId")
                        .IsUnique();

                    b.ToTable("Barn");

                    b.HasData(
                        new
                        {
                            BarnId = 1,
                            Adresse = "Storgata 1",
                            Alder = 7,
                            Land = "Norge",
                            Navn = "Emma Hansen",
                            NiceScore = 85,
                            ØnskelisteId = 1
                        },
                        new
                        {
                            BarnId = 2,
                            Adresse = "Fjellveien 23",
                            Alder = 5,
                            Land = "Norge",
                            Navn = "Oliver Johansen",
                            NiceScore = 70,
                            ØnskelisteId = 2
                        },
                        new
                        {
                            BarnId = 3,
                            Adresse = "Skogsveien 45",
                            Alder = 10,
                            Land = "Norge",
                            Navn = "Sofie Berg",
                            NiceScore = 95,
                            ØnskelisteId = 3
                        });
                });

            modelBuilder.Entity("NissensVerksted.Models.Leke", b =>
                {
                    b.Property<int>("LekeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aldersgruppe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AlvId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LekeId");

                    b.HasIndex("AlvId");

                    b.HasIndex("Status");

                    b.ToTable("Leker");

                    b.HasData(
                        new
                        {
                            LekeId = 1,
                            Aldersgruppe = "3-6 år",
                            AlvId = 1,
                            Antall = 50,
                            Beskrivelse = "Håndlaget tredukke",
                            Navn = "Tredukke",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Innpakket"
                        },
                        new
                        {
                            LekeId = 2,
                            Aldersgruppe = "7-12 år",
                            AlvId = 2,
                            Antall = 30,
                            Beskrivelse = "Fjernstyrt bil med lys",
                            Navn = "Robotbil",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing"
                        },
                        new
                        {
                            LekeId = 3,
                            Aldersgruppe = "0-3 år",
                            AlvId = 3,
                            Antall = 100,
                            Beskrivelse = "Myk bjørn",
                            Navn = "Kosedyr",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Montering"
                        },
                        new
                        {
                            LekeId = 4,
                            Aldersgruppe = "10+ år",
                            AlvId = 1,
                            Antall = 20,
                            Beskrivelse = "1000 brikker",
                            Navn = "Puslespill",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Design"
                        },
                        new
                        {
                            LekeId = 5,
                            Aldersgruppe = "5-10 år",
                            AlvId = 2,
                            Antall = 15,
                            Beskrivelse = "Rød sparkesykkel",
                            Navn = "Sparkesykkel",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Innpakket"
                        },
                        new
                        {
                            LekeId = 6,
                            Aldersgruppe = "4-8 år",
                            AlvId = 3,
                            Antall = 80,
                            Beskrivelse = "Samling med eventyr",
                            Navn = "Bok: Eventyr",
                            OpprettetDato = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Innpakket"
                        });
                });

            modelBuilder.Entity("NissensVerksted.Models.Ønske", b =>
                {
                    b.Property<int>("ØnskeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ErOppfylt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .HasColumnType("TEXT");

                    b.Property<int>("LekeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prioritet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ØnskelisteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ØnsketDato")
                        .HasColumnType("TEXT");

                    b.HasKey("ØnskeId");

                    b.HasIndex("LekeId");

                    b.HasIndex("ØnskelisteId", "LekeId")
                        .IsUnique();

                    b.ToTable("Ønsker");

                    b.HasData(
                        new
                        {
                            ØnskeId = 1,
                            ErOppfylt = false,
                            Kommentar = "Ønsker meg blå robotbil!",
                            LekeId = 2,
                            Prioritet = 1,
                            ØnskelisteId = 1,
                            ØnsketDato = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 2,
                            ErOppfylt = false,
                            Kommentar = "Elsker å lese!",
                            LekeId = 6,
                            Prioritet = 2,
                            ØnskelisteId = 1,
                            ØnsketDato = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 3,
                            ErOppfylt = false,
                            LekeId = 5,
                            Prioritet = 3,
                            ØnskelisteId = 1,
                            ØnsketDato = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 4,
                            ErOppfylt = false,
                            Kommentar = "Vil ha tredukke!",
                            LekeId = 1,
                            Prioritet = 1,
                            ØnskelisteId = 2,
                            ØnsketDato = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 5,
                            ErOppfylt = false,
                            Kommentar = "Helst brun bjørn",
                            LekeId = 3,
                            Prioritet = 2,
                            ØnskelisteId = 2,
                            ØnsketDato = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 6,
                            ErOppfylt = true,
                            LekeId = 4,
                            Prioritet = 1,
                            ØnskelisteId = 3,
                            ØnsketDato = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ØnskeId = 7,
                            ErOppfylt = false,
                            Kommentar = "Robotbil med lys!",
                            LekeId = 2,
                            Prioritet = 2,
                            ØnskelisteId = 3,
                            ØnsketDato = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NissensVerksted.Models.Ønskeliste", b =>
                {
                    b.Property<int>("ØnskelisteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpprettetDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ØnskelisteId");

                    b.ToTable("Ønskelister");

                    b.HasData(
                        new
                        {
                            ØnskelisteId = 1,
                            BarnId = 0,
                            OpprettetDato = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tittel = "Emma sin ønskeliste"
                        },
                        new
                        {
                            ØnskelisteId = 2,
                            BarnId = 0,
                            OpprettetDato = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tittel = "Oliver sin ønskeliste"
                        },
                        new
                        {
                            ØnskelisteId = 3,
                            BarnId = 0,
                            OpprettetDato = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tittel = "Sofie sin ønskeliste"
                        });
                });

            modelBuilder.Entity("NissensVerksted.Models.Barn", b =>
                {
                    b.HasOne("NissensVerksted.Models.Ønskeliste", "Ønskeliste")
                        .WithOne("Barn")
                        .HasForeignKey("NissensVerksted.Models.Barn", "ØnskelisteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ønskeliste");
                });

            modelBuilder.Entity("NissensVerksted.Models.Leke", b =>
                {
                    b.HasOne("NissensVerksted.Models.Alv", "AnsvarligAlv")
                        .WithMany("Leker")
                        .HasForeignKey("AlvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnsvarligAlv");
                });

            modelBuilder.Entity("NissensVerksted.Models.Ønske", b =>
                {
                    b.HasOne("NissensVerksted.Models.Leke", "Leke")
                        .WithMany("Ønsker")
                        .HasForeignKey("LekeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NissensVerksted.Models.Ønskeliste", "Ønskeliste")
                        .WithMany("Ønsker")
                        .HasForeignKey("ØnskelisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leke");

                    b.Navigation("Ønskeliste");
                });

            modelBuilder.Entity("NissensVerksted.Models.Alv", b =>
                {
                    b.Navigation("Leker");
                });

            modelBuilder.Entity("NissensVerksted.Models.Leke", b =>
                {
                    b.Navigation("Ønsker");
                });

            modelBuilder.Entity("NissensVerksted.Models.Ønskeliste", b =>
                {
                    b.Navigation("Barn")
                        .IsRequired();

                    b.Navigation("Ønsker");
                });
#pragma warning restore 612, 618
        }
    }
}
